### ISSUE TITLE
Refine Colours and font sizing

### ISSUE THREAD

**Issue by NDoolan360** [NDoolan360/NDoolan360-Site#8]
https://www.realtimecolors.com/dashboard?colors=d8f3ed-192926-4dffd2-2e2531-d8f3ed&fonts=Oxygen%20Mono-Josefin%20Sans

Colours:

```css
:root[data-theme="light"] {
  --text: #0c2721;
  --background: #d6e6e3;
  --primary: #00b386;
  --secondary: #d7ceda;
  --accent: #0c2721;
}
:root[data-theme="dark"] {
  --text: #d8f3ed;
  --background: #192926;
  --primary: #4dffd2;
  --secondary: #2e2531;
  --accent: #d8f3ed;
}
```

Font sizing:
```css
body {
  font-family: 'Josefin Sans';
  font-weight: 400;
}

h1, h2, h3, h4, h5 {
  font-family: 'Oxygen Mono';
  font-weight: 700;
}

html {font-size: 100%; /* 16px */}

h1 {font-size: 3.053rem; /* 48.8px */}

h2 {font-size: 2.442rem; /* 39.04px */}

h3 {font-size: 1.954rem; /* 31.2px */}

h4 {font-size: 1.563rem; /* 24.96px */}

h5 {font-size: 1.250rem; /* 20px */}

small {font-size: 0.800rem; /* 12.8px */}
```
